version: "2.2"
services:
  worker:
    image: servicebe
    build:
      context: ./service
      dockerfile: Dockerfile
    working_dir: /home
    entrypoint: [./run.sh]
    env_file:
      - service.env
    environment:
      MODE: "api"
    depends_on:
      - redisstack

  api:
    image: servicebe
    working_dir: /home
    entrypoint: [./run.sh]
    env_file:
      - service.env
    environment:
      MODE: "submitworker"
    depends_on:
      - redisstack

  nginx-server:
    image: nginx-load-balancer
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 6002:80
    restart: unless-stopped
    depends_on:
      - query
      - redisstack

  redis:
    image: redis/redis-stack
    restart: always
    ports:
      # - 6379:6379 
      - 8002:8001
    volumes:
      - ./data/redis:/data
      
